### ISSUE TITLE
Support bindable at the plan level as well as the service

### ISSUE THREAD

**Issue by avade** [openservicebrokerapi/servicebroker#104]
**Context**

https://github.com/cloudfoundry/cloud_controller_ng/issues/567

https://www.pivotaltracker.com/n/projects/966314/stories/115985379

*As a service author I want to be able to flag `bindable` at the plan level, so I can have granular control* 

---

The bindable attribute should work by selecting the most specific value. For example:

Service level: bindable=true
Plan level: bindable=false
Result: the plan is **not** bindable

Service level: bindable=false
Plan level: bindable=true
Result: the plan is bindable

Bindable at the plan level should be optional and default to the service level attributes value.

```
{
  "services": [{
    "name": "fake-service",
    "id": "acb56d7c-XXXX-XXXX-XXXX-feb140a59a66",
    "description": "fake service",
    "tags": ["no-sql", "relational"],
    "requires": ["route_forwarding"],
    "max_db_per_node": 5,
    "bindable": true,
    "metadata": {
      "provider": {
        "name": "The name"
      },
      "listing": {
        "imageUrl": "http://example.com/cat.gif",
        "blurb": "Add a blurb here",
        "longDescription": "A long time ago, in a galaxy far far away..."
      },
      "displayName": "The Fake Broker"
    },
    "dashboard_client": {
      "id": "398e2f8e-XXXX-XXXX-XXXX-19a71ecbcf64",
      "secret": "277cabb0-XXXX-XXXX-XXXX-7822c0a90e5d",
      "redirect_uri": "http://localhost:1234"
    },
    "plan_updateable": true,
    "plans": [{
      "name": "fake-plan",
      "id": "d3031751-XXXX-XXXX-XXXX-a42377d3320e",
      "description": "Shared fake Server, 5tb persistent disk, 40 max concurrent connections",
      "max_storage_tb": 5,
      "bindable": true, #optional
      "metadata": {
        "cost": 0,
        "bullets": [{
          "content": "Shared fake server"
        }, {
          "content": "5 TB storage"
        }, {
          "content": "40 concurrent connections"
        }]
      }
    }]
      }
    }]
  }]
}
```

**Comment by avade** [comment]
Planned for Service Broker API 2.11.

**Comment by pmorie** [comment]
So the use case for this is to support within the same service some plans that are bindable, and some that are not?  I don't dispute that this is valid, but I wonder if you can provide an example of where this would be useful.

**Comment by shalako** [comment]
@pmorie Here's the use case we're working to support: 

A service provider wants to enable app developers to provision databases on servers. They also want to enable some teams to share a database server for multiple databases. Rather than grant sufficient permissions to the developers to create new databases on a server, the service providers wants to enable app developers to use the same marketplace workflows to create servers and to choose which servers a database is created on. 

The service broker will offer one service offering and two plans. The first plan provisions dedicated (private) servers, without a database; we'll call this plan the "server plan." These service instances are not bindable, and only some teams have access to this plan. 

The second plan provisions databases on a server; we'll call this the "database plan." By default, databases will be provisioned on a system-wide shared server. However, if an app developer has access to a service instance for a dedicated server (provisioned from the "server plan"), the app developer can provide an identifier for the service instance (service instance name?) as an arbitrary parameter with the provision request for the database plan. In this way, app developers can share a dedicated server and manage lifecycle of databases on it, all using marketplace primitives.

**Comment by petereberlein** [comment]
We have a very similar use case: We have a broker that has a service plan to create database schemas. Right now these schemas are created in a database that is configured externally. It would be great if we could introduce a database plan with which you can create the database and reference its instance when creating a schema. 

While it might be nice if the database plan could be flagged as "non bindable", but the other aspect of how to reference the database instance when creating the schema instance is to me even more important. Certainly, you could just pass it as a parameter in the create-service call for the schema but then the cloud controller knows nothing about the dependency between the two and would not complain if you had a bound schema instance but try to delete the database instance.

Would be great if these kind of parent-child relations between service instances could be expressed more explicitly, e.g. by extending the create-service command by an additional parameter to specify it as a "child" of another service instance.

What do you think about this?

**Comment by shalako** [comment]
Hello Peter,
My challenge with this is that it only supports a relationship between objects known to the same service broker. Often, service instances depend on other service instances managed by other brokers. Currently this relationship is established via the parameters field, but could be a first-class relationship known to the platform. Currently CF doesn't support something like service-to-service bindings, but occasionally this has come up in the past.

**Comment by petereberlein** [comment]
Isn't this yet another reason why such a reference should be an explicit parameter on the create-service command to enable the cloud controller to keep track of these relations? If it is only put in the parameter field, a service broker could leverage this information broker internally (which is already insufficient as explained above) but not cross-broker.

**Comment by gberche-orange** [comment]
I understand the ``bindeable at pla level`` feature is mostly a hint to UIs to not accept/propose binding user requests to some service instances of specific service plans.

The current work on [JSON schema](https://docs.google.com/document/d/1-IKI-PwPnhtbK0su1UzWA_UoyaCjL8S2d6ky3Xmuwvg/edit#heading=h.g87gk1t0z7p0) could be used to support this use-case without adding specifics to the SB API

See the following [bindeable prototype](https://github.com/orange-cloudfoundry/servicebroker/blob/dialogue-tree-schema/tests/schema/use_cases/bindeable/billing-account.feature#L11-L14) referencing [schemas](https://github.com/orange-cloudfoundry/servicebroker/tree/dialogue-tree-schema/tests/schema/use_cases/bindeable). See more background in [readme](https://github.com/orange-cloudfoundry/servicebroker/tree/dialogue-tree-schema/tests/schema)

(Sorry for late feedback on this.)
If it is not too late, it might make sense to wait a bit before merging https://github.com/cloudfoundry/docs-services/pull/149 into openservicebrokerapi/servicebroker

I'll try to see how the JSON schema can used to express composition of services instances among a given service broker (i.e. a expressing constraints over a series of user requests, rather than a single request)

**Comment by shalako** [comment]
Closing as it is in 2.11
