### ISSUE TITLE
Remove some CF-isms

### ISSUE THREAD

**Issue by avade** [openservicebrokerapi/servicebroker#115]
## Problem 

*As a service broker author I can choose to ignore CF-isms in the Service Broker API specification and see that these are deprecated, but still available, just not as a top level attribute*

## History

https://github.com/openservicebrokerapi/servicebroker/pull/83

## Next steps

1. Create proposal document
1. Review on OSBAPI WG call

## Details
Branch with spec changes: https://github.com/duglin/servicebroker/tree/CFisms
- Including "context profile" doc: https://github.com/duglin/servicebroker/blob/CFisms/profile.md

Diff of changes: https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms

OLD: Google doc for the original proposal profile: https://docs.google.com/document/d/15X9LWzZw8EF5TSufqsdrBcdlALr-6rWdMo3FVCbjrfs/edit#heading=h.9gcbm1qmz9wc

**Comment by duglin** [comment]
The basic idea here is:
- deprecate the existing CF-specific properties from the message flows (org and space)
- create a new "context" property (json object) to take the place of org/space. Its an opaque json object that the platform can use to share info about the context in which the operation is taking place.
- define a "Context Profile" that includes "recommended" properties that should be included based on the platform.

Changes to the old spec can be seen here:  https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms

Draft of OSB API Context Profile doc: https://docs.google.com/document/d/15X9LWzZw8EF5TSufqsdrBcdlALr-6rWdMo3FVCbjrfs/edit#

**Comment by gberche-orange** [comment]
thanks @duglin for this work and sorry for late feedback on this.

`` PUT /v2/service_instances/:instance_id/service_bindings/:binding_id`` contains CF-ism in multiple fields: ``app_guid`` and ``bind_resource.app_guid``. Where would be the context object be located in this case (does not seem yet illustrated into the the ``duglin:CFisms``  branch) ?.

The specs currently support different http headers that provide brokers meta-data about the platform calling them and spec version used:
* ``X-Api-Info-Location``
* ``X-Broker-API-Version``

I wonder whether you considered passing the proposed ``context.platform`` rather as an http header instead of a context object field, such as 
``X-Broker-API-Version=1.12;profile=cloudfoundry`` (or refinements with inspiration from the [Content-Type format](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html))
This might enable having if needed multiple context objects (e.g. at differing depth) in a same payload without duplicating the profile meta-data.

How to service brokers indicate the profile(s) they support ? Shouldn't we specify a catalog meta-data field (supported API versions and their profiles), or alternatively explore leveraging the mode general JSON schema expressivity drafted in #59 (e.g. with the [catalog-attached schema in the HTTP-based format](https://github.com/openservicebrokerapi/servicebroker/blob/7285960dae30481736f11a4e08177c9e676e884c/tests/schema/use_cases/modeled-against-http/backup-request.json#L4-L4)

Is there cases where SB responses would be differing depending on the profile used in received request (such as ommiting syslog_drain or differing route format) ? Should we then specify this case in the proposed spec change?

Folllowing are some more minor feedbacks over the ``duglin:CFisms``  branch even if this might no yet be the final PR:


https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms#diff-bb9940da4a4abf26c3e4fbffdd3c763dR13 
 > defined in this document in order to aide in interoperability across

should read "aid" ? http://grammarist.com/spelling/aid-aide/

https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms#diff-bb9940da4a4abf26c3e4fbffdd3c763dR122

> +The following table specifies which properties MUST appear in each API:
> +
> +Request API | Properties
> +----------- | ----------
> +`POST /v2/service_plan_visibilities` | `organization_guid`
> +`PUT /v2/service_instances/:instance_id` | `organization_guid`<br>`space_guid`
> +`PATCH /v2/service_instances/:instance_id` | `organization_guid`<br>`space_guid`

As a side note, it would make sense to complement this logic expressed in natural language with executable specification such as a formal REST API specification for the OSB and subsets for platform specific
profiles, similar to the [cf-swagger](https://github.com/cloudfoundry-incubator/cf-swagger/blob/master/descriptions/cloudfoundry/service_broker/service_broker.json) 

/CC @maximilien

https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms#diff-b9973092b8c988fb543b7aea4ea0211cR285

>  cf curl /v2/service_plan_visibilities -X 'POST' -d '{"service_plan_guid":"1113
>         "organization_guid": "aaaa1234-da91-4f12-8ffa-b51d0336aaaa",
>         "organization_url": "/v2/organizations/c54bf317-d791-4d12-89f0-b56d0936cfdc"
>         "context": {
> 

I understand this is CF CC API and not SB API

**Comment by maximilien** [comment]
Generally concur with describing any CF APIs as Swagger or Open APIs descriptions. Our attempt of the [v2.5 version of the CF service broker](cf-swagger/descriptions/cloudfoundry/service_broker/service_broker.yaml) is in the [CF-Swagger](https://github.com/cloudfoundry-incubator/cf-swagger) incubation project.

Best,

Max

**Comment by gberche-orange** [comment]
@avade maximilien 

There is an going exploration on whether the open API-based schema could be used:
* not only to 
  * specify the service broker API and its validate implementations such as brokers
  * specify the cloudfoundry profile discussed here
* but also to have brokers specify their supposed input parameters format, and returned service bindings formats, etc...

Refer to #59 and the Input params design proposal  [section on REST API schema](https://docs.google.com/document/d/1-IKI-PwPnhtbK0su1UzWA_UoyaCjL8S2d6ky3Xmuwvg/edit#bookmark=id.drnf0e8i6xmv) for this exploration and consider join the [related call on friday 13/1, 4pm GMT / 8am PST](https://groups.google.com/d/msgid/open-service-broker-api/CAJcey07gXGQHhMHkaBPckThz0hY8U9rJo0jJmHZprpV2mNDQeg%40mail.gmail.com?utm_medium=email&utm_source=footer)

**Comment by duglin** [comment]
> On Jan 10, 2017, at 3:22 PM, Guillaume Berche <notifications@github.com> wrote:
> 
> thanks @duglin <https://github.com/duglin> for this work and sorry for late feedback on this.
> 
> PUT /v2/service_instances/:instance_id/service_bindings/:binding_id contains CF-ism in multiple fields: app_guid and bind_resource.app_guid. Where would be the context object be located in this case (does not seem yet illustrated into the the duglin:CFisms branch) ?.
> 
I'm not sure I would consider the “app_guid” to be CF specific. The word “app” might be and perhaps we could consider a new word, but I think passing in some kind of unique identifier that represents the entity to which the service will be bound seems pretty generic to me. I guess I would just make sure that its optional, or can be “”, to indicate that there is no specific object its being bound to - more like a global service (e.g. LB perhaps).  What do others think?
> The specs currently support different http headers that provide brokers meta-data about the platform calling them and spec version used:
> 
> X-Api-Info-Location
> X-Broker-API-Version
> I wonder whether you considered passing the proposed context.platform rather as an http header instead of a context object field, such as
> X-Broker-API-Version=1.12;profile=cloudfoundry (or refinements with inspiration from the Content-Type format <https://www.w3.org/Protocols/rfc1341/4_Content-Type.html>)
> This might enable having if needed multiple context objects (e.g. at differing depth) in a same payload without duplicating the profile meta-data.
> 
That's an interesting idea. I like the idea of not duplicating the information (or running the risk of them being different), but do we have cases where we expect the “context” field to show up more than once in a message?  I suppose, in the future, there might be some kind of operation that takes two objects in different contexts but would it be good or bad if one were in CF and one were in Kubernetes?  For clouds that support more than one platform this seems possible, no?
> How to service brokers indicate the profile(s) they support ? Shouldn't we specify a catalog meta-data field (supported API versions and their profiles), or alternatively explore leveraging the mode general JSON schema expressivity drafted in #59 <https://github.com/openservicebrokerapi/servicebroker/issues/59> (e.g. with the catalog-attached schema in the HTTP-based format <https://github.com/openservicebrokerapi/servicebroker/blob/7285960dae30481736f11a4e08177c9e676e884c/tests/schema/use_cases/modeled-against-http/backup-request.json#L4-L4>Good question. One could argue that people shouldn’t try to register a CF broker with Kube so its not an issue, but w/o some indication in the Catalog metadata about what platforms/profiles a broker supports there’s no programmatic way to know this. What do other people think about adding a fields to the Catalog metadata indicating which profiles it supports? if I have time today I’ll work on a mod to the PR so people can see what it looks like.
> Is there cases where SB responses would be differing depending on the profile used in received request (such as ommiting syslog_drain or differing route format) ? Should we then specify this case in the proposed spec change?
> 
I'm not sure about this. I think you might be right that the messages between the platform and a broker might differ between brokers but this could be true for any number of reasons, not just the profile. E.g. perhaps it’ll use different URLs based on whether the broker is on-prem vs in the wild internet.  My initial reaction to this is that platforms will do whatever they need to do to make things work and as long as the spec doesn’t preclude them from doing something then they’re free to do so. At the same time, I wouldn’t want the spec to go out of its way to suggest that people should do stuff like this, which is what I think text like this would do.  But, I’m not totally against the idea if other people what it - but I would suggest we make it a pretty generic statement and not tied to the profile info - so perhaps a new issue to have the discussion?
> Folllowing are some more minor feedbacks over the duglin:CFisms branch even if this might no yet be the final PR:
> 
> master...duglin:CFisms#diff-bb9940da4a4abf26c3e4fbffdd3c763dR13 <https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms#diff-bb9940da4a4abf26c3e4fbffdd3c763dR13>
> defined in this document in order to aide in interoperability across
> 
> should read "aid" ? http://grammarist.com/spelling/aid-aide/ <http://grammarist.com/spelling/aid-aide/>Fixed!
> master...duglin:CFisms#diff-bb9940da4a4abf26c3e4fbffdd3c763dR122 <https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms#diff-bb9940da4a4abf26c3e4fbffdd3c763dR122>
> +The following table specifies which properties MUST appear in each API:
> +
> +Request API | Properties
> +----------- | ----------
> +POST /v2/service_plan_visibilities | organization_guid
> +PUT /v2/service_instances/:instance_id | organization_guid
> space_guid
> +PATCH /v2/service_instances/:instance_id | organization_guid
> space_guid
> 
> As a side note, it would make sense to complement this logic expressed in natural language with executable specification such as a formal REST API specification for the OSB and subsets for platform specific
> profiles, similar to the cf-swagger <https://github.com/cloudfoundry-incubator/cf-swagger/blob/master/descriptions/cloudfoundry/service_broker/service_broker.json>
> /CC @maximilien <https://github.com/maximilien>I think producing a swagger version of the spec would be a good idea. Can you open up a new issue for that since I think that’s a bigger issue than this one?
> master...duglin:CFisms#diff-b9973092b8c988fb543b7aea4ea0211cR285 <https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:CFisms#diff-b9973092b8c988fb543b7aea4ea0211cR285>
> cf curl /v2/service_plan_visibilities -X 'POST' -d '{"service_plan_guid":"1113
> "organization_guid": "aaaa1234-da91-4f12-8ffa-b51d0336aaaa",
> "organization_url": "/v2/organizations/c54bf317-d791-4d12-89f0-b56d0936cfdc"
> "context": {
> 
> I understand this is CF CC API and not SB API
> 
Fixed

**Comment by petereberlein** [comment]
>>  PUT /v2/service_instances/:instance_id/service_bindings/:binding_id contains CF-ism in multiple fields: app_guid and bind_resource.app_guid. Where would be the context object be located in this case (does not seem yet illustrated into the the duglin:CFisms branch) ?.

> I'm not sure I would consider the “app_guid” to be CF specific. The word “app” might be and perhaps we could consider a new word, but I think passing in some kind of unique identifier that represents the entity to which the service will be bound seems pretty generic to me. I guess I would just make sure that its optional, or can be “”, to indicate that there is no specific object its being bound to - more like a global service (e.g. LB perhaps).  What do others think?

To me the app_guid looks as platform specific as org_guid or space_guid - if those are put in a context object then the app_guid should go into one as well. Interestingly the app_guid was already moved to a sub-element (bind_resource) quite some time ago, maybe this element could take the role of the context? Either being even renamed to context or keeping the name but handling it like a context object?

>>  The specs currently support different http headers that provide brokers meta-data about the platform calling them and spec version used:
 X-Api-Info-Location
 X-Broker-API-Version
 I wonder whether you considered passing the proposed context.platform rather as an http header instead of a context object field, such as
 X-Broker-API-Version=1.12;profile=cloudfoundry (or refinements with inspiration from the Content-Type format <https://www.w3.org/Protocols/rfc1341/4_Content-Type.html>)
 This might enable having if needed multiple context objects (e.g. at differing depth) in a same payload without duplicating the profile meta-data.

> That's an interesting idea. I like the idea of not duplicating the information (or running the risk of them being different), but do we have cases where we expect the “context” field to show up more than once in a message?  I suppose, in the future, there might be some kind of operation that takes two objects in different contexts but would it be good or bad if one were in CF and one were in Kubernetes?  For clouds that support more than one platform this seems possible, no?

Following my above comment, I do envision multiple context objects within one request. At the same time, I do not see one request to contain contexts from different platforms (who should send such a request?). Therefore, I'm in favor of Guillaume's proposal to put the platform identifier into a header. After all, version information is already there and what sense would it make to put the platform in one place and its version in another?

**Comment by duglin** [comment]
> On Jan 13, 2017, at 4:20 AM, Peter Eberlein <notifications@github.com> wrote:
> 
> PUT /v2/service_instances/:instance_id/service_bindings/:binding_id contains CF-ism in multiple fields: app_guid and bind_resource.app_guid. Where would be the context object be located in this case (does not seem yet illustrated into the the duglin:CFisms branch) ?.
> 
> I'm not sure I would consider the “app_guid” to be CF specific. The word “app” might be and perhaps we could consider a new word, but I think passing in some kind of unique identifier that represents the entity to which the service will be bound seems pretty generic to me. I guess I would just make sure that its optional, or can be “”, to indicate that there is no specific object its being bound to - more like a global service (e.g. LB perhaps). What do others think?
> 
> To me the app_guid looks as platform specific as org_guid or space_guid - if those are put in a context object then the app_guid should go into one as well. Interestingly the app_guid was already moved to a sub-element (bind_resource) quite some time ago, maybe this element could take the role of the context? Either being even renamed to context or keeping the name but handling it like a context object?
> 
To me org/space represent things are may only exist in one platform, so they’re on the chopping block. However, the higher order concept they represent (context) is not something that’s specific to just one platform. Even if a platform doesn’t have “contexts” because everything is global/shared, they can still think of it as “they have just a single context”, or even null.  Its not a stretch for them.

I view “app” more like “context” than “org” - meaning its just the high-order concept of the “thing” we’re binding to. This “thing” is at the heart of this API and most platforms (ignoring the use case of a service that’s not bindable).

> The specs currently support different http headers that provide brokers meta-data about the platform calling them and spec version used:
> X-Api-Info-Location
> X-Broker-API-Version
> I wonder whether you considered passing the proposed context.platform rather as an http header instead of a context object field, such as
> X-Broker-API-Version=1.12;profile=cloudfoundry (or refinements with inspiration from the Content-Type format https://www.w3.org/Protocols/rfc1341/4_Content-Type.html <https://www.w3.org/Protocols/rfc1341/4_Content-Type.html>)
> This might enable having if needed multiple context objects (e.g. at differing depth) in a same payload without duplicating the profile meta-data.
> 
> That's an interesting idea. I like the idea of not duplicating the information (or running the risk of them being different), but do we have cases where we expect the “context” field to show up more than once in a message? I suppose, in the future, there might be some kind of operation that takes two objects in different contexts but would it be good or bad if one were in CF and one were in Kubernetes? For clouds that support more than one platform this seems possible, no?
> 
> Following my above comment, I do envision multiple context objects within one request. At the same time, I do not see one request to contain contexts from different platforms (who should send such a request?). Therefore, I'm in favor of Guillaume's proposal to put the platform identifier into a header. After all, version information is already there and what sense would it make to put the platform in one place and its version in another?
> 

Can you give an example of a case where you see more than one context in a request?

-Doug

**Comment by avade** [comment]
As per the call yesterday, we agreed to move this into the "validation through implementation" phase.

I will report back once the work is scheduled on the CloudFoundry side.

**Comment by duglin** [comment]
I've updated the branch by rebasing it on the latest master/spec and added more docs in the Kubernetes section of the context docs - including an example.

**Comment by pmorie** [comment]
@jminter @jmrodri Please review

**Comment by duglin** [comment]
I've updated the branch to "deprecate" org/space rather than remove them. I've also rebased it so that there the diffs against spec.md not _spec.md.

@shalako in "Updating a service instance" the org/space were under the "previous_values" property, so that's where I placed `context`.  However, it doesn't seem like the context (org/space) can change during this call so would it make more sense to put `context` as a top-level property instead of nested under `previous_values` ?  Then we're consistent across the other APIs.

**Comment by shalako** [comment]
Only `plan_id` and `parameters` are mutable, so it's misleading that `service_id`, `organization_id`, and `space_id` are under `previous_values`. CF doesn't currently persist parameters so doesn't have the previous values to send with the update, but we could eventually add `previous_values.parameters` to the spec.

I suppose it makes sense to add `context` as a top-level key, since that's probably where we should have put org and space in the first place. We should deprecate `previous_values.organization_id` and `previous_values.space_id`.

The presence of `previous_values.service_id` is just redundant. I can't remember why we put it there. It isn't mutable and it's also present as a top-level key. I'd suggest we remove it from the spec  now or deprecate it at a minimum.

**Comment by jmrodri** [comment]
Line 34 should read '**it is** strongly RECOMMENDED that they adhere' instead of 'is it strongly RECOMMENDED that they adhere'

**Comment by jmrodri** [comment]
@duglin @pmorie overall the proposal looks good. There was one typo I mentioned above. The deprecation of the parameters makes for a good intermediate step to support the context. I like that the context is an object making it possible to add further fields if required by a particular platform.

**Comment by duglin** [comment]
To be clear on @shalako's proposal, I think its to add the following to this change:
- Put 'context' at a top-level property
- Deprecate: previous_value.service_id|organization_id|space_id

And I'd like to discuss this on today's call.

@jmrodri I updated the context profile doc with your proposed typo/fix.

**Comment by duglin** [comment]
On today's call it was agreed to make "context" optional.
Alex will investigate whether we can loosen the spec to allow for org/space to be strings instead of uuid/guids.

**Comment by gberche-orange** [comment]
> Alex will investigate whether we can loosen the spec to allow for org/space to be strings instead of uuid/guids.

There are several CF-specific brokers that rely on the org/space to be guids so that they can use the received guids against the CF API. See related thread on the cf-dev@ list http://cf-dev.70369.x6.nabble.com/cf-dev-Do-your-service-brokers-leverage-the-Org-and-Space-fields-in-the-broker-API-td6056.html

The org/space fields are currently specified in the cloufoundry specific context object.

@avade are you considering to loosening the org/space fields format as string to make it common with K8S and potentially platform independent ?

**Comment by mattmcneeney** [comment]
The latest spec on master states that:

- **provision** (`PUT /v2/service_instances/:instance_id`) has two **required** body parameters:
  - `organization_guid` (string)
    _The platform GUID for the organization under which the service is to be provisioned. Although most brokers will not use this field, it may be helpful for executing operations on a user's behalf._
  - `space_guid` (string)
    _The identifier for the project space within the platform organization. Although most brokers will not use this field, it may be helpful for executing operations on a user's behalf._

- **update** (`PATCH /v2/service_instances/:instance_id`) has two **optional** body parameters:
  - `previous_values.organization_guid` (string)
    _ID of the organization specified for the instance._
  - `previous_values.space_guid` (string)
    _ID of the space specified for the instance._

As far as I can tell, there is no definition of `guid` in the spec, so as of now, platforms should be able to use these fields however they please. CF could provide it's org and space IDs, whilst Kubernetes could provide the namespace twice (for now).

In order to remove the "CF-ism", we plan on adding an **optional** `context` object to these requests whilst leaving the existing org/space parameters as they are today (_required_ for provision, _optional_ for update).

In version 3 of the spec, we can then remove these parameters and make the context parameter required.

---

Does this make sense to everyone?

@pmorie will this be acceptable for your kubernetes use cases (providing namespace in the existing org/space fields, and anything else in the `context` object)?

If we are happy to proceed with this, @duglin would you be able to update your branch and begin the PR?

**Comment by duglin** [comment]
@mattmcneeney yes this is what our Kube impl does today (uses the namespace in the org and space) but as of now it uses the NS UID not its name - which is problematic because searching for a Kube namespace by UID isn't possible, its done by name.  

Even if the spec doesn't define GUID that doesn't necessarily mean its ok to use a string instead. The spec isn't as spec-ish as it should be so not having a reference to the RFC that defines GUID isn't a surprise.  I think the bigger concern is what will existing Brokers do with "foo" instead of a GUID.  If the CF community doesn't see an issue then great - but if they do then we may have more work to do (or perhaps just the kube folks do).

@gberche-orange the comments about existing brokers assuming that org/space are GUIDs and using that to talk back to CF isn't really the full answer to the question. If those brokers will only work when talking to CF then we're ok since CF will also send them as GUIDs. The real question is whether or not those brokers work in an env where its not CF, or where they don't try to talk back to the platform. And in those cases do they care about the shape of the org/space values? I'm hoping that those brokers who do not try to talk to the platform will do not GUID validation on the value and just treat it as an opaque string.  (To be honest, I'm not sure why a broker talking to CF would do validation in the first place to make sure its a GUI, but that's a different topic).

**Comment by petereberlein** [comment]
At least the fields have a "_guid" in the name, so although technically they are only specified as strings, it is a fair assumption that people might expect an actual GUID and would be more or less surprised to find something else.

**Comment by mattmcneeney** [comment]
I agree with @petereberlein that the `_guid` is misleading. Is this enough to render this approach invalid?

If the easiest path forward  would be to simply accept that, then since the spec already states the type for these fields as `string`, to move forward on this issue we could:
1. Note this misleading field name in the spec (if needed?)
1. Add the optional `context` property
1. Discuss deprecating these fields and making `context` required when v3 arrives

If this is OK with the CF community ( @avade @shalako ) and would help other use cases (like the Kubernetes use case @duglin described) then in my opinion this is a reasonably good approach. Thoughts?

**Comment by avade** [comment]
SGTM @mattmcneeney

**Comment by duglin** [comment]
Slight expansion/modification of the proposal:
1 - note the fields are misleading ( guid vs string )
2 - make it clear that they are strings and while its RECOMMENDED they be GUIDs, there is no requirement they be so.  Which means brokers are expected to treat them as opaque strings
3 - deprecate org/space now
4 - add optional `context`

I'd prefer to deprecate them now so that we can remove them entirely when v3 happens and not keep them around any longer than necessary.

**Comment by shalako** [comment]
LGTM

There's a common use in CF of guid in field names and type is always string. This has never seemed misleading before, but if it is to others we can certainly clarify in the fields description. 

I agree with deprecating them now. It's as easy as updating the field description to say so. 

Shannon

**Comment by mattmcneeney** [comment]
Sounds good @duglin. Are you happy to update your branch and create a PR for review?

**Comment by petereberlein** [comment]
I'm totally in favour for deprecating these fields and adding the context (optional or not). But I feel that adding a note that a field that is called something_guid does actually not contain a guid is somehow an incompatible change.

**Comment by zrob** [comment]
I understood that context was being added as an optional property until 3.0.

The current branch shows it as required for `PUT /v2/service_instances/:instance_id`.

**Comment by duglin** [comment]
Did i mess up? I dont see a * in the table. Which line do you see it on?

**Comment by zrob** [comment]
Sorry, looks like a false alarm.

When I clicked on the commit above: https://github.com/duglin/servicebroker/commit/ebfe264e121faf618311fa35a1ef16d4fd0754a1 it shows an asterisk

But when I clone your repo and checkout the branch I don't see it.

Proof I'm not *entirely* crazy:
![image](https://cloud.githubusercontent.com/assets/1703742/25247279/46d4b2a0-25bf-11e7-8683-3c4c55c4d4b3.png)

**Comment by duglin** [comment]
fixed a typo found by @samze and rebased.

**Comment by mattmcneeney** [comment]
Good news, this has now been merged into the Cloud Controller in CF! [PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/818)

@duglin Please could you create a PR from your `remove-cfisms` branch so we can get this into the spec?

Thanks!

**Comment by duglin** [comment]
we've been having some talks over in the kube svc-cat sig and its becoming clear that some of the definitions used by CF do not align nicely with kube. For example, the definition of an app. To CF an app is clearly defined and has a single GUID.  In Kube, its less clear. The best we could say is that an app is a LabelSelector that tells us what pods in the system make up the app. But even that's not totally accurate either.  My point is that as we continue to work on the svc-cat stuff I think we're going to find other places besides just org and space where some tweaking will be needed.

For example, another spot that just popped up is app_guid on the binding request. Because Kube doesn't have a GUID that's a perfect fit for this its not clear what to put in there. This make me think that we may need to put something more complex than a GUID in the `bind_resource` json object in the binding request - and I'm going to open an issue/PR for that soon.

In the meantime, I'm thinking that as part of this issue/PR we should consider renaming the "context profile" to something more like "platform profile". This would then allow us to specify platform specifics that are not just related to 'context' - for example, we could specify that for kube the `bind_resource` needs to include other things like a LabelSelector - if that's what we think is needed. So this should just be a minor wording change to this new doc we're creating, but I wanted to know what people thought before I started to work on it.  Any objection?

**Comment by mattmcneeney** [comment]
@duglin That sounds sensible enough to me, but should we try to get the context change in now (since it's in the official CF repos) and do that in a follow up PR?

**Comment by duglin** [comment]
I just updated my branch with the following changes:
- rebased
- renamed the "context profile" doc to just be "profile". This will allow us to include non-context related profiling info in there later on - such as how to use oAuth - w/o having to create another doc.
- this will also provide a place for us to include other Platform specific things, such as Platform specific "bind_resource" properties, if we ever want to define those.

Please see the links in the first comment for the links.

**Comment by mattmcneeney** [comment]
This looks good to me @duglin. I think it may be time to create a PR for everyone to look through?
