### ISSUE TITLE
Deprovision does not clarify how to handle active bindings

### ISSUE THREAD

**Issue by jmrodri** [openservicebrokerapi/servicebroker#127]
While reading the specification it was not clear to me what happens to bindings during a deprovision call. Are the bindings orphaned? or are they actively deleted by the broker? or should deprovision be disallowed if there are active bindings?

**Comment by avade** [comment]
The implementation in Cloud Foundry is that the platform will not request a broker to delete the service that has existing bindings.

However, the broker could also choose to be defensive about not deleting a service with existing bindings.

**Comment by pmorie** [comment]
I think that we should at least clarify this in the spec; it currently says two different things in two different places.

@avade since you're most familiar with the current behavior, would you mind making a PR to clarify?

**Comment by duglin** [comment]
I'd like to suggest the following outline of a proposal:
- clarify in the spec that it is RECOMMENDED that platforms delete all Bindings prior to deleting an Instance
- brokers MAY support deleting an Instance that still has bindings (causing a cascading delete), but if they don't then we'll specify the exact error that MUST be returned
- platforms MAY attempt to delete an Instance that still has Bindings, but if they get the well defined error then they MUST delete the bindings first.

**Comment by duglin** [comment]
On this week's call we decided to force platforms to delete all bindings before they could delete an instance. I think there's a problem with this approach. Since there is no requirement or method by which a broker can return the list of existing bindings, if the platform loses track of all of the bindings for an Instance, it could get into a situation where it can never delete an instance because it can't delete bindings it doesn't know about.  

While the more clean approach (no cascading deletes) might be preferred, given the current state of the spec I'm not sure we can make that change, so I'm inclined to think we're back to what I proposed in the previous comment.  I'll add this to the agenda for next week's f2f.
