### ISSUE TITLE
Include organization_guid and space_guid in deprovision and bind/unbind requests

### ISSUE THREAD

**Issue by luksa** [openservicebrokerapi/servicebroker#155]
The `organization_guid` and `space_guid` should be included in the requests, just like the `service_id` and `plan_id` are.

This would allow the broker to retrieve instance metadata even when it isn't stored centrally, but per-tenant (per-space in OSB terminology). 

Here's a more detailed description of why we need this:

The Messaging-as-a-Service broker allows provisioning of messaging addresses collocated in the same messaging infrastructure (the infrastructure is per-tenant). The broker currently doesn't use its own storage for storing instances - instead, it simply creates k8s resources directly. The resources themselves represent the instances. Being multi-tenant, it stores these resources across different k8s namespaces. To retrieve a service instance by uuid therefore currently requires scanning all those namespaces in order to find the namespace the instance is stored in.

I'd like to not have to use an additional storage layer just for storing what would essentially be duplicate data just for efficient retrieval, since the platform knows all the data I need (`organization_guid` and `space_guid`) and it could easily pass it on to the broker. 

WDYT?

**Comment by avade** [comment]
We are trying to move away from having org/space guids as top level properties: https://github.com/openservicebrokerapi/servicebroker/issues/115

You can see the current proposal from @duglin (https://github.com/duglin/servicebroker/tree/CFisms) that moves these fields into a context object (https://github.com/duglin/servicebroker/blob/CFisms/context-profiles.md).

Perhaps the context object could also be sent in deprovision and bind/unbind requests.

**Comment by jagadish-kb** [comment]
@avade  any idea when context object would be getting added to deprovision/bind/unbind requests as well ? Any specific reason it was left out and added only for PUT/PATCH methods.

**Comment by mattmcneeney** [comment]
@jagadish-kb The `context` object was added for provision service instance, update service instance and bind service instance. It was left out of unbind service instance and delete service instance as those DELETE requests don't support request bodies, and we didn't want to have to find a way to encode this information in a query parameter.

We're hoping that brokers can either use their own state or rely on other components to remember any contextual information they need in order to successfully unbind or deprovision.

**Comment by jagadish-kb** [comment]
@mattmcneeney Thanks for the response.

Our service broker is stateless and we don't persist any state at the moment. Reason: Actual state might get out of synch with CC & provisioning (BOSH) System (cases of orphaned instances/Orphaned Deployments) & if broker also starts maintaining this mapping then data reconciliation has to happen across CC, Broker & the provisioning system. So at-least to minimise this reconciliation effort, since broker as the name suggests is just brokering we go back to CC if we need instance info or the provisioning system (like BOSH) to figure out any deployment info & get the actual state. 

We would want to avoid broker having to go back to Cloud Controller as we have requests from platforms other than CF, where they want to use our broker in their environments as well. So in this regard we want to be compliant with OSBAPI as much as possible. Consumers from other platforms  are ready to send few additional context params as part of Delete requests but since the spec does not have them in, wanted to check. 

With regards to HTTP DELETE not allowing request bodies is debatable as the [HTTP Spec](https://tools.ietf.org/html/rfc7231#section-4.3.5) does not call this out explicitly. Interesting conversation around this on [stackoverflow](https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request) .

**Comment by jagadish-kb** [comment]
@mattmcneeney  @avade 
any update on the above issue?  
We want to be compliant with OSBAPI however the above issue is forcing us to be stateful, which certainly requires a bigger effort in terms of implementation and also ensuring the state that is maintained in the broker is in synch with actual deployment state (corner cases related to orphan deployments/ service instances). Ideally it will help us a lot if even DELETE method carries this context information. I am sure, there could be at least a few other service broker implementation who are stateless (mostly those who provision BOSH based deployments) & this will be certainly good have.

Would appreciate if you can please provide a resolution on the above & let us know if the above would be considered to be done in future or not.

**Comment by duglin** [comment]
While I can certainly understand wanting to have org and spec flow on the requests, I don't think we should include a body on DELETE - I've heard too many times about httpd servers or proxies that don't support it that it seems risky to do so.

I'd like to understand the usecase a bit more... how does the org/space help you find the instances across the k8s namespaces?

**Comment by n3wscott** [comment]
> I've heard too many times about httpd servers or proxies that don't support it that it seems risky to do so.

I would hope we would embrace the forward direction of specs and standards rather than anchor ourselves to today's broken implementations. But that said, a body on delete feels real weird.

In regards to stateless brokers, the direction we are taking seems to me to require some small amount of state to be maintained by the broker for the broker to be useful. Some state is definitely required to handle async requests. I think async requests are the future of brokers and sync requests are a mistake to support. Therefore I believe all brokers must have state and stateless brokers should be discouraged.

**Comment by jagadish-kb** [comment]
@n3wscott For handling Asynch requests, the spec already has a mechanism in place & one can handle asynch requests being completely stateless. The `operation` attrib that is returned back as part of asynch request's response is played back as part of the `lastoperation` polling. So whatever minimal state is required can be base64 encoded, sent as part of provision/deprovision/update response & the same gets played back. So for async request handling one need not maintain state per-se. 
But limitations such as above certainly would make one to be stateful.

@duglin 
> I'd like to understand the usecase a bit more... 

Our broker implementation is currently tied to CF, but we have a requirement for it to be CF agnostic & also handle requests coming in K8s/other homegrown consumers, allowing for cross platform service consumption.
Now org Id & space id are certainly not required for instance identification but instead required to identify the service instance backup/restore information in S3/Swift stores. The file paths to service instance backup/restore info have been prefixed with org/space id along with instance id.  This is done for easier listing/access at org/space level if required. Now backup/restore are not in the purview of the spec, but these are extension use cases which our broker implementation has built around. This info from S3/Swift stores must also be deleted post instance deletion. This is just one scenario, we have couple of other custom tasks which are platform specific ex., creation /deletion of security groups for service instance as in CF.
You might ask, in the erstwhile CF service broker API as well the org/space guid was not flowing as part of DELETE and how were we managing. - So in our current state, for such requests where this info is missing we query back CF & retrieve this information. If at-least platform info is passed, it certainly would help. This can be avoided, if this info flows automatically.

I know it certainly feels weird to have a payload on DELETE. Now i only suggested including context info in DELETE, as it will make this uniform across requests. However, if its felt wrong to do this then why not pass it as part of Query params? The spec can say context flows either in body or query params. Ass a consumer of this spec I certainly feel there is value in passing this info in all requests.

Obviously the above problem completely goes off, if one were to be stateful. If being stateful is the recommendation of the Spec it certainly helps to call this out explicitly in the documentation as then teams implementing the same don't have to debate / discuss & spend time on this design consideration.

**Comment by mattmcneeney** [comment]
You make a good point @jagadish-kb that the specification should take more of a stance on whether or not brokers should be stateful, and that even if synchronous operations were deprecated, there are measures in place to allow statelessness.

When we were adding the `context` object to provision/update/bind, we did discuss adding this information as an encoded query parameter, but due to the unbound length of it the group were unhappy with this approach (I think @duglin or @fmui had some useful points here).

Regarding your specific use case; since service instances are created in a single org and space, and the service instance ID should be unique, can't you delete any backups in S3 that start with `<instace-id>-` and simply ignore the `<org-id>-<space-id>` suffix?

**Comment by jagadish-kb** [comment]
@mattmcneeney - the path in S3 contains the org/space guid as prefixes for easier filtering of meta info. These were prefixed to the paths in S3 for the lack of SQL sort of query capabilities. So yeah, had we not prefixed these ORG/space guids to instance id, it would have been straight forward as you said in the above but now we have to have some round about way of figuring it out. 

We handle both bosh based &  docker based deployment models. As a minimal store, we can probably go the route of storing these values in deployment properties for bosh & environment variables for Docker & avoid a dedicated persistent store just for storing such minimal attribs. So we can have a work-around, but It would be good if these basic params accompany all APIs.

**Comment by mattmcneeney** [comment]
The `context` object now includes the `organization_guid` and `space_guid`.

This only applies for provision, update and bind requests though, as we haven't found a solution for including context in DELETE requests yet (unbind and deprovision). That discussion can be tracked in #201.
