### ISSUE TITLE
Orphans handling and idempotency

### ISSUE THREAD

**Issue by nilebox** [openservicebrokerapi/servicebroker#182]
(Originally posted [in Service Catalog](https://github.com/kubernetes-incubator/service-catalog/issues/781#issuecomment-299339307))

Why does the OSB spec have requirements for DELETE requests in case of a potential _orphan_ (provisioning timeout, for example) instead of requiring Service Broker to provide **idempotency** guarantees?

For example (from the [Orphans section](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans)):

> To mitigate orphan instances and bindings, the marketplace SHOULD attempt to delete resources it cannot be sure were successfully created, and SHOULD keep trying to delete them until the broker responds with a success.

Why marketplace doesn't retry provisioning a resource (or creating a binding) instead of deleting a potential orphan? Marketplace _does_ provide **instanceId** to Service Broker, so it's easy to implement idempotent request handling in Service Broker without any changes in the API.

Retrying with "at least once" semantics seems to be a much better user experience than just trying once and giving up.

**Comment by ash2k** [comment]
Another case where current behaviour is an issue. Suppose datastore behind the marketplace is lost/corrupt and a backup is restored. Say, backup is 1 hour old and does not include information about some instances. Marketplace clients may reissue requests to recreate instances that marketplace "forgot" (what else they can do?). It all should be ok because, say, databases, provided by "DB-as-a-service" broker are still there and broker can just return information about them. However, if marketplace gets an error/timeout from the broker it has to try to DELETE that instance, deleting a database with client's data. Not great :)

A better approach might be to define a "list" API on brokers so that marketplace can detect orphans and an operator can make decisions if something needs to be updated in marketplace storage or deleted via delete request to the broker.

**Comment by nilebox** [comment]
As mentioned in [Service Catalog issue](https://github.com/kubernetes-incubator/service-catalog/issues/821), it's not only about timeouts and data corruption, but also about more common case of restarting the marketplace (during update to a new version, for example) during ongoing provisioning/binding requests.

This case could be covered by downtime and nightly updates ofc, but just adding retries would eliminate this issue completely.

**Comment by mattmcneeney** [comment]
@nilebox is this still an issue?

**Comment by nilebox** [comment]
@mattmcneeney probably not for v2 due to backward compatibility requirements, but something to keep in mind for v3.

Closing.
