### ISSUE TITLE
Verify that the registry->service instance APIs align with CF's definition

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#25]
https://docs.cloudfoundry.org/services/api.html
Basically, the service registry->service broker calls related to #24 
https://docs.cloudfoundry.org/services/api.html#provisioning

**Comment by duglin** [comment]
add unit testcases too

**Comment by bmelville** [comment]
Hey @duglin,

Can you clarify what you mean by service registry in this model?

**Comment by duglin** [comment]
I think you guys are using the term "service controller" - I mean the thing that keeps track of the list of available service brokers that are registered in the env.  I can't bring myself to use the "controller" word :-)  it just doesn't fit to me.  In CF's case they use the term "cloud controller" because to them the CC is the brains(controller) of CF, but not just for the service registry piece of it.  I think "service registry" is more descriptive to a newbie.

**Comment by bmelville** [comment]
Ah okay, we have been using the term service registry as the name for the thing that stores service definitions (i.e., the thing that backs the service broker's catalog).

I think the controller is more than just a registry. In fact it doesn't really store a registry of anything because it's just aggregating from elsewhere, but it is controlling the injection of bindings into whatever context it runs in.

**Comment by duglin** [comment]
The entire "naming" issue is something I added to the agenda for the f2f - we need to get agreement just to avoid confusion.  But in general, yes I mean the component that manages the list of registered services, and manages the list of service instances, and manages the list of service bindings, and injects them into the app. 

I'm not sure we get into what's behind a service broker - that's an impl detail.

**Comment by bmelville** [comment]
Sounds good, definitely worth having a unified vocab.
