### ISSUE TITLE
Generalize 'requires' field of services and binding types

### ISSUE THREAD

**Issue by angarg12** [openservicebrokerapi/servicebroker#313]
Right now the spec supports 4 types of bindings. For each binding it defines the valid output data format.

These 4 types are very broadly applicable but they seem to be specific for CF use cases. On it's current state the spec would need to be changed to support any additional use case.

Trying to generalize this behavior is in line with the work that has been done in other parts of the spec to remove CFisms.

Right now there are two proposals about how to define the supported bindings and their structure:

* Use JSON schema like service parameters.
* Use profiles like context object.

Independently of the approach chosen, we can also discuss how we want to roll out these changes. I'm thinking about two possibilities:

* A two stage approach: The new solution is introduced, old fields are marked a deprecate. Deprecate fields would be removed in a major version bump.
* A one stage approach: The old fields are removed and the new ones introduced in a major version bump.

Personally I prefer using profiles and rolling out the changes in two steps. It would involved more work but we could roll out the change sooner and get it tested, and reduce the risk of a major version release.

Let's hear your opinion!

**Comment by mattmcneeney** [comment]
I'd like to get @zrob's opinion on this one. As far as I am aware, in CF the `requires` field (an array supporting `syslog_drain`, `route_forwarding` and `volume_mount`) is used so that we can know in advance what type of binding the service is providing, and so that we can interpret the response body when creating a binding.

If this is the case, then providing an alternative way for brokers to advertise the 'type' of service they provide seems like a reasonable step. I'm not sure whether this should be a schema representation of the binding response or just another place to advertise platform-specific binding types.

The problem with the latter is that it is going to encourage platform-specific brokers, which we want to avoid. It would be good to hear if Kubernetes has a plan to support similar services to route services and volume mounts moving forward.

**Comment by zrob** [comment]
Requires is used as sort of a pseudo-authorization mechanism more so than to interpret the response.  

One example is that if a service that does not require `syslog_drain` in the catalog, actually does return a syslog drain url, then the platform will note this and refuse to allow the syslog functionality.

It helps operators understand what services are doing on their platform and to opt-out of including services that might make undesired changes to app behaviors.  Imagine a service that claims to provide a message queue, but is also draining all logs to some unexpected location that may need security auditing.

This means the requires value is tightly coupled to response data in the binding.  So I'm not sure what the value in platform specific require fields would be, b/c they currently are all tightly coupled to a spec feature, not a platform feature.

**Comment by mattmcneeney** [comment]
Added removing the `requires` field to the [Ideas for v3](https://github.com/openservicebrokerapi/servicebroker/wiki/Ideas-for-v3) page. Closing here.
