### ISSUE TITLE
OSBAPI Project Feedback

### ISSUE THREAD

**Issue by avade** [openservicebrokerapi/servicebroker#322]
Last week we had three interesting bits of feedback from ISV's integrating with the service broker API:

1. It wasn't obvious that their existing service brokers would work with the OSBAPI specification
1. They thought the API was developer-facing and wanted to expose service brokers directly to developers via a CLI
1. They thought the project provided an API server and didn't realise it was a specification only
1. From the website, it was difficult to find the specification 

I suggest that we do the following:

1. Modify the landing page at https://openservicebrokerapi.org to clarify the above points
1. Make it easier to find the spec from the landing page

**Comment by mattmcneeney** [comment]
Agreed!

**Comment by duglin** [comment]
Clarity is good - go for it.

**Comment by avade** [comment]
As per our call, I will start to draft changes and share with the group in this issue.

**Comment by leonwanghui** [comment]
Hi, sorry to turn out this out-of-date issue, but I'm quite interested at this collaborative meeting, so is this call public and periodically? Thanks!

**Comment by MHBauer** [comment]
@leonwanghui call details available here https://github.com/openservicebrokerapi/servicebroker/wiki/Weekly-Call

**Comment by leonwanghui** [comment]
Got it, same one with what I known...发自我的iPhone------------------ Original ------------------From: Morgan Bauer  <notifications@github.com>Date: 周六,1月 27,2018 09:14To: openservicebrokerapi/servicebroker <servicebroker@noreply.github.com>Cc: Leon Wang <wanghui71leon@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [openservicebrokerapi/servicebroker] OSBAPI Project Feedback(#322)@leonwanghui call details available here https://github.com/openservicebrokerapi/servicebroker/wiki/Weekly-Call

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openservicebrokerapi/servicebroker","title":"openservicebrokerapi/servicebroker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openservicebrokerapi/servicebroker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MHBauer in #322: @leonwanghui call details available here https://github.com/openservicebrokerapi/servicebroker/wiki/Weekly-Call"}],"action":{"name":"View Issue","url":"https://github.com/openservicebrokerapi/servicebroker/issues/322#issuecomment-360947138"}}}

**Comment by leonwanghui** [comment]
@MHBauer Got it, same one with what I known...

**Comment by mattmcneeney** [comment]
Closing as this information is now available in the readme.
