### ISSUE TITLE
Community Feedback: Changes in ways that services/plans are deprecated, removed, and renamed

### ISSUE THREAD

**Issue by pmorie** [openservicebrokerapi/servicebroker#323]
I'm opening this issue to seek feedback from the community on the subject of how services and plans are deprecated/removed/renamed.

Currently:

- Human readable names of services and plans are mutable
- There is no way for broker authors to indicate that a service or plan is deprecated and will be removed in the future

Names being mutable presents difficulties for kubernetes.  Kubernetes has a single coordinate for individual API resources called a 'name'.  Names of objects are not mutable.  As a result for the time being we have had to make some design choices that aren't amazing for users in order to deal with the possibility of name changes.

In our recent F2F meeting for the API working group, we discussed the possibility of:

- Deprecating the mutability of names
- Adding a field to services and plans allowing broker authors to indicate that a service is deprecated and will be removed in a future release

This would allow broker authors to handle name changes in a more user-friendly manner by marking a service or plan as deprecated and making a new service or plan with the new name.

I'd be very curious to know what broker authors think of this idea.

**Comment by mattmcneeney** [comment]
Some feedback from some service broker authors in the CF world:
* Being able to change the names of services and plans that are shown in CLIs/UIs is useful for marketing purposes and for being able to show that some things are in _alpha_ or _beta_
* If we were to deprecate the mutability of names, this would probably be OK as long as there was another place in the catalog where the 'marketing name' of the service/plan could be specified
* We currently have _displayName_ field in the service-level metadata, which could be used for this purpose, however we would need another field (so we have one for CLIs and one for Web UIs)
* There was some confusion over why we need both a _name_ and _displayName_ field already, since the spec. requires each service and plan to have a unique ID

**Comment by duglin** [comment]
I would prefer to reuse "displayName" as the "marketing name" for both CLI and WebUIs - otherwise I'm not sure it will be very easy to explain the proliferation of names. Although, I'm not sure what it means for the CLI other than its just another column that's displayed when listing the services. I wouldn't expect people to ever type it as input.

**Comment by mattmcneeney** [comment]
@duglin What would users be using as the input then? The service name still? If so, I think it is important that that field remains immutable. Lots of folks write scripts to manage basic lifecycle events, so I think we should strive to ensure whatever comes after _cf create-service XXX_ remains the same for a service at all times.

**Comment by duglin** [comment]
I agree, they should use the "service name" on the cli. I don't think using the "display/marketing name" makes sense from a CLI perspective because it'll have spaces and other non-cli-friendly chars. 

re: immutable... that's really the heart of the issue. Are people ok with the value they specify on the cli changing during the lifetime of the service? Your first bullet from https://github.com/openservicebrokerapi/servicebroker/issues/323#issuecomment-337293960 implied they might be ok with it, but then your latest comment says the opposite.  Unless your first bullet is talking about the display/marketing-name?  In which case I think the current spec already supports it.

Your 2nd bullet confuses me. If names are mutable are you then assuming that the display/marketing-name is immutable? Would anything except the ID be immutable?

**Comment by mattmcneeney** [comment]
I don't think I articulated those points well! Depending on the design, these points _may_ be conflicting, but we know that:
* Service broker authors would like a place to show (to both CLI and Web UI users) a 'marketing name', so that they can inform users of, for example, when a service moves from alpha to beta
* CLI users often use scripts for automation, so it is important that whatever is used in CLI commands stays consistent (across a progression of a service from 'alpha' to 'beta').

If we agreed to keep the service _name_ immutable, then one option would be to simply expose the _metadata.displayName_ field in the CLI (for example, in a table). This could change at any time (so a service named `mysql` could have a display name of `MySQL (alpha)`, where the display name could change in the future, but not the service name).

Hope that makes a bit more sense!

**Comment by duglin** [comment]
yes, and showing the displayName in a table (where cliName would also be another column) was my assumption.

As for immutable value in the cli... it seems to me we only have two choices:
1 - leave it as is (name is immutable)
2 - allow name to be mutable but then the cli allows for people to use the ID. But this is really an implementation decision and not one for the spec to decide.

**Comment by mattmcneeney** [comment]
Closing as this was opened to collect community feedback almost 2 years ago.
