### ISSUE TITLE
OSB validation toolchain

### ISSUE THREAD

**Issue by arschles** [openservicebrokerapi/servicebroker#363]
My colleague @Haishi2016 has written a [test suite](https://github.com/Haishi2016/osb-checker) to validate a broker for OSB compatibility. He's willing to donate it to the OSB WG as part of the official validation tooling.

This issue is to begin discussion to move code over, etc...

**Comment by mattmcneeney** [comment]
🙌  Thanks @arschles - this is great.

Once we've moved this over to this repository, we will have to make sure that all spec changes include the required changes to the test suite. We may also want to bump header versions etc in the test suite on each release.

**Comment by Haishi2016** [comment]
The test suite is organized into version folders so that each version can be maintained in isolation. 
The suite has a mock OSB server that complies with the current spec. It could be useful to test service catalog / marketplace implementation. I’m currently using the mock server to test my Service Fabric service catalog implementation.

On the other hand, to test a different OSB implementation, test configurations need to be updated to include implementation-specific information such as service ids and plan ids. The test suite is data-driven, so it can be extended to support different service classes from a specific OSB implementation. I envisioned we should have configurations for key OSB implementations checked into this repo.

I'm open to make continuous contributions to the suite wherever it will land.

**Comment by avade** [comment]
+1 from me on the concept, this looks like it will be extremely useful for service broker developers. 

Things I think we should have an answer to before moving the project into the OSBAPI org:

1. How will we keep this in sync with the spec? Should it support pre-release versions?
1. Who will be a maintainer outside of the PMC? (assuming @Haishi2016)
1. Technical quality - does this look maintainable if the original author wasn't available? what would need to change, if anything?

Questions are open, so anyone with thoughts please comment!

**Comment by arschles** [comment]
I'm open to make contributions along with @Haishi2016.

My opinions to @avade's questions are below

>How will we keep this in sync with the spec? Should it support pre-release versions?
 
Initially, I don't think the checker should support pre-release versions. When spec changes (patch or greater) are finalized, I believe a PR should be submitted to the checker repository alongside the final spec change PR. 

>Who will be a maintainer outside of the PMC? (assuming @Haishi2016)

Ideally, there will be someone or people on the PMC who will be one of the maintainers (not sure if that was implied below), but either myself or @Haishi2016 (depending on whether he's willing - I'll let him comment) can do it.

>Technical quality - does this look maintainable if the original author wasn't available? what would need to change, if anything?

It's currently written in node.js javascript using familiar (IMO) test functions. Additionally, the code looks straightforward to me. I don't think much would need to change if the codebase stays organized as it is now.

I'm biased, so I'm interested to hear what someone else thinks after they peek at the code.

**Comment by Haishi2016** [comment]
I do plan to make continuous contributions. 

This is my first time to use Mocha, so there could be places that are not done in a "pro" way. I'm open to any refactors to make it better quality.

**Comment by arschles** [comment]
Thanks for letting us know @Haishi2016. It sounds like you should be a maintainer on this new project after it's moved.

I believe someone on the PMC and I should also be maintainers.

**Comment by duglin** [comment]
+1 to creating a new repo in our org for this

**Comment by arschles** [comment]
awesome. I was asked what name the repo could be called. `broker-validator` sounds good to me. other suggestions?

**Comment by Haishi2016** [comment]
Has the repo been created?

**Comment by Haishi2016** [comment]
I didn't want to over-engineer this. I think when new releases come out, copying the tests will be fine because the old version will be in freeze.The downside, of course, is a bug fix in early versions needs to be prorogated into later versions. I think it should be rare, though. 

I don't see significant value of making tests additive. But I'm open to refactoring common routines to make them work across versions.

**Comment by marciogh** [comment]
> It's currently written in node.js javascript using familiar (IMO) test functions. Additionally, the code looks straightforward to me. I don't think much would need to change if the codebase stays organized as it is now.

I'm happy with this in NodeJS and Mocha. I can easily create test result reports and integrate with our CI, to support all OSB developers around the organization.

**Comment by mattmcneeney** [comment]
We now have [test suites](https://github.com/openservicebrokerapi/servicebroker#testing-conformance-to-the-open-service-broker-api) linked to from the readme!
