### ISSUE TITLE
The definition of "Credentials" needs to be clarified.

### ISSUE THREAD

**Issue by mihnjong** [openservicebrokerapi/servicebroker#438]
According to https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#credentials,

it says that:
Credentials are a set of information used by an Application or a user to utilize the Service Instance. If the Service Broker supports generation of `credentials` it **MUST** return credentials in the response for a request to create a Service Binding. 

Google Service Broker supports `credentials` for services like Pubsub, but some services do not provide any credentials. In this case, the Google Service Broker simply returns no `credentials`. With the assumption that this behavior is allowable, can we correct the spec accordingly?

**Comment by duglin** [comment]
I don't think the spec, as it stands today, precludes what you're saying. If there are no credentials then there won't be a "credentials" property. Am I missing something?

**Comment by kibbles-n-bytes** [comment]
Ah, so is the intention of that sentence that there shouldn't be any out-of-band credentials negotiation? And that if credentials are necessary in order to use an instance, they must be exposed to the user through the `credentials` struct of the binding response?

To me, a completely literal reading of that sentence implies that if a Service Broker *ever* generates a `credentials` payload for any of its service offerings, all service offerings must be authenticated through credentials, and these credentials will be surfaced in the bind request's response payload.

**Comment by duglin** [comment]
I'm not following. While there can always be some out of band agreement for anything, I don't think we can ever stop that, if you're trying to live within the bounds of the spec then yes the auth used to access the service instance will leverage the creds returned in the binding. @kibbles-n-bytes why is that strange?

If you're focused on the "ever" and "any" part of your 2nd paragraph, and you're saying we need to add words to make it clear that the sentence is really on a per-service (or even instance) basis, then ok - that can't hurt.  Is that what you meant?

**Comment by jeremyrickard** [comment]
@kibbles-n-bytes I think you mentioned in the call that this should have more discussion. I'd be up for discussing this.

**Comment by duglin** [comment]
Assigned to: @kibbles-n-bytes

**Comment by mattmcneeney** [comment]
Closing this issue as I think this is a no-op. It's perfectly valid for a service to return an empty/non-existant `credentials` object in the binding response, but the app would need to know ahead of time where the backing service is running and how to connect with it.

Since the `credentials` response field is optional, there is no reason why this could not be set up out-of-band (though we don't recommend this!).
