### ISSUE TITLE
Returning multiple fields on a bind request

### ISSUE THREAD

**Issue by mattmcneeney** [openservicebrokerapi/servicebroker#440]
According to the spec, a service binding can return several pieces of information today:
```
credentials
syslog_drain_url
route_service_url
volume_mounts
```

I don't know of any service broker that returns more than one of these fields. The spec. requires specific strings in the `requires` field of the catalog when some of these are returned, but there are no rules about returning multiple.

I don't think CF would handle this very well, and I don't think anything other than `credentials` is supported by svc-cat. Can we look at tidying this up in the spec?

@duglin do you have any use case from your end?

**Comment by duglin** [comment]
I believe that CF has a separate CLI cmd/api for creating route services. This means that CF would never request creds and route service bindings at the same time. I don't know about volumes, so it could be that just syslog bindings are the only ones that can be done at the same time as a cred binding in a CF world.  IBM does currently have services that support route services but we can't tell for sure if they support cred bindings at the same time since there is no "requires" flag to indicate it.

However, I would be a bit nervous about a breaking change to the spec that would preclude any existing broker that might support multiple from working - even though it would be a bit odd given CF may not support it :-)

**Comment by mattmcneeney** [comment]
This is supported in CF, and having re-read the spec, I don't think we need to add any more clarity around this. So I'll close this issue.
