### ISSUE TITLE
Can instance_id be reused after orphan mitigation finished?

### ISSUE THREAD

**Issue by nilebox** [openservicebrokerapi/servicebroker#447]
The OSB spec is not clear about whether `instance_id` is reusable after the initial provisioning request has failed and orphan mitigation (https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans) has succeeded.

To give an example, let's say that the initial provisioning request has timed out. According to the OSB spec orphan mitigation is required in this case. But once it has been done, you want to try provisioning again (hoping that this time the request won't timeout). The question is whether it's okay to send a provisioning request with the same `instance_id` in that case, or you have to generate a new one.

Same applies to all `5xx` errors.

**Comment by arschles** [comment]
I believe that it should be able to be reused for these reasons:

1. I don't believe there are any other instances where brokers are expected to remember {binding, instance} IDs
2. ... so if an orphan mitigation has completed, the broker should not know about that ID at all
3. There isn't any language that I know of in the spec that says that IDs cannot be reused for any other reason

@nilebox can you cross-reference the issue in the OSB repo? Would be helpful for context

**Comment by carolynvs** [comment]
I agree with the sentiment that the current behavior, requiring the user to recreate the instance, goes against "the kubernetes way". The way I'm reading the spec, it should be safe to retry after orphan mitigation succeeds.

I would prefer that svc-cat retries, and while it may take a while, or in the other scenario (400 bad request) the user fixes the instance parameters, eventually the instance can be successfully provisioned without hacky workarounds. That fits better into my mental model of how kubernetes apis should handle

**Comment by nilebox** [comment]
Original issue in Service Catalog: https://github.com/kubernetes-incubator/service-catalog/issues/1715

**Comment by duglin** [comment]
Revisiting this one... couple of things that come to mind:
- we never really know when the orphan mitigation is completed. If its a long running process to clean everything up, the Platform might send another request with the same ID while the Broker still knows about the old one. This could cause the Broker to reject the request due to a conflict. 
- once a resource is deleted the spec talks about sending a "410 Gone". Per the HTTP spec it says that "This condition is expected to be considered permanent". However, it also says "It is not necessary to mark all permanently unavailable resources as "gone" or to keep the mark for any length of time -- that is left to the discretion of the server owner." I suspect this last part was added to make it clear that the server doesn't need to remember all resources forever - which would be a huge burden.  But, nevertheless, from an OSBAPI perspective, it appears we expect a 410 for at least some period of time.
- from an auditing perspective, it seems to me that reusing the same ID for two resources that are technically unrelated could cause some problems, or at least confusion when trying to analyze things.
- there's nothing in the spec that says a Broker can't remember all old instances forever - if nothing else to return a 410 Gone.  This implies to me that Platforms need to be prepared for this situation.

If we did add language to the spec to allow instanceID to be reused it seems we'd need to:
- clarify the relationship between the use of 410 and the create() ops
- add something about the case where the old resource is still known to the broker - what kind of error would be returned, or what the platform is expected to do about it?  Just retrying over and over until the Broker eventually cleans things up feels a bit risky since the Broker may actually never do so (which is valid).

My current thinking is that we should:
- say Platforms SHOULD create a new ID each time (mainly because I think they need to support it anyway due to case where a Broker chooses remembers old resources forever)
- say Brokers MAY support Platforms reusing IDs, but clearly define what error MUST be returned if it detects a reused ID and can't support it

**Comment by mattmcneeney** [comment]
That thinking sounds sensible to me @duglin. I agree with the SHOULD from a CF perspective, but happy to add the MAY with some predefined error code.

**Comment by nilebox** [comment]
> we never really know when the orphan mitigation is completed.

Orphan mitigation is no different from the normal deletion.
Broker should only return `state: success` on `last_operation` when deprovisioning has finished. If it returns success earlier, IMO it's a bug in the broker and violation of the spec.

**Comment by nilebox** [comment]
My alternative proposal would be to:

- say Brokers SHOULD support Platforms reusing IDs, and clearly define what error MUST be returned if it detects a reused ID and can't support it

It's not necessary to define what platform should do in the case when broker doesn't support reusing IDs. It's obvious that there will be some handling of the rejected request, but I would leave up to concrete platform implementation.

**Comment by mattmcneeney** [comment]
@jberkhahn is this still important to you?

**Comment by jberkhahn** [comment]
sure. It seems to me to make the most sense that deprovisioned IDs are the same as non-existent

**Comment by mattmcneeney** [comment]
PR inbound! Let me know what you think
