### ISSUE TITLE
Clarify 'cluster ID' part of kube profile

### ISSUE THREAD

**Issue by pmorie** [openservicebrokerapi/servicebroker#478]
I don't think the change merged in #466 is specific enough, and I worry that we're backing Kubernetes integration with this API into a corner.

I'm primarily worried that the addition to the spec isn't clear enough about what 'unique' means. Does it mean that each kube cluster has to have a single, immutable, unique ID forever? If so, I think we should change the language. I worry that someone could change the ID of a kube cluster and break compliance with the spec. It's going to be basically impossible to guarantee that a unique value for an instance of a cluster never changes.

**Comment by duglin** [comment]
I view this as an impl detail for kube to decide. The text describes it as:
- - -
The unique identifier for the Kubernetes cluster from which the request was sent.
- - -
Which means it just needs to match what the current cluster ID is since this will mainly be used when communicating back to the platform to identify which cluster we're talking about. If the platform provides it bad data then things will break so its really only hurting itself. Or put another way, this isn't really about interop with other platforms/impls - this is about interop with itself. 

But, if we need more text explaining that I'm ok adding it. In particular, if you think we need to talk about how while it might not be 100% static for all time/space due to unforeseen circumstances, it is expected to be pretty static.  Would that help?

**Comment by pmorie** [comment]
I'm just wondering if this concept is one we can really deliver on.

Say someone goes and changes the cluster ID somehow in a kubenetes cluster. If this happens, doesn't it break everything in progress with every broker? If so, we need to rethink whether this field is mandatory. I'm _really_ hesitant to write checks in the spec that are going to be hard to deliver on in platforms.

**Comment by duglin** [comment]
I'm curious to know why you think this value in Kube would ever really change? Most people will never even know about it.  But yes, if someone is silly enough to change something (similar to going in and changing something directly in k8s's etcd) they can break stuff that might be in-flight - but it would have to be really lucky timing to get it just right. But in the end, we can't protect people from themselves.

Either way, I think that would be a possible change in Kube (meaning adding logic to control when/if someone can change the value), not a change in the spec. From a spec perspective I think the platform needs to make this decision for itself.

**Comment by duglin** [comment]
I took an AI from last week's call to add some text clarifying this field - totally forgot about it, but I think that should address your concerns.  Keep an eye out for it soon...

**Comment by pmorie** [comment]
I'm good with #480
