### ISSUE TITLE
Reverse lookup of service instance id during provisioning

### ISSUE THREAD

**Issue by jakkahub** [openservicebrokerapi/servicebroker#514]
We are trying to get service name of an instance id during provisioning. We know, instance id is generated by the platform when creating a service instance. This is passed to the service broker but the name isn’t. We can call the CC API `GET /v2/service_instances/:guid` to get the service name of an instance id.

But this didn't worked for us, since we are trying to get service name before the service broker returns with 202 to CF as it need to know that the broker has accepted the request.

Here is our flow and we are trying to make step 3 work in between steps 2 and 4.
1) Submit service provisioning command cf create-service
2) CF calls service brokers `PUT /v2/service_instances/:instance_id` endpoint
3) Service broker’s service instance creation implementation gets service name for instance guid from CF using `GET /v2/service_instances/:guid`
4) Service broker returns below json with status code `202 Accepted` to CF
_{
  "dashboard_url": "http://example-dashboard.example.com/9189kdfsk0vfnku",
  "operation": "task_10"
}_
5) CF polls the Service Instance Last Operation Endpoint for operation status

We need service name that was provided in `cf create-service` command to create service instance on our PAAS.

Is there any solution or workaround for our use case? Or else any option to pass all command line parameters in `cf create-service` command to the service broker’s provisioning endpoint ?

**Comment by duglin** [comment]
I can see value in knowing the name as well, however we'd need to deal with issues like renaming. IMO whenever you allow a user to pick the value of something that is meaningful to them (like 'name') then you have to allow for fat-fingers and that means renames. Delete-n-recreate, to be blunt, sucks as a model.  So, to me update() would need to support changing the name - for instances. Do we need this on bindings too?

So, I'm leaning towards option 1.  Kube doesn't use the user-provided name as the Kube "name" so its not static.

**Comment by duglin** [comment]
@mattmcneeney do you have time to work on a PR for this? If not, I might be able to get someone from our side to take a try

**Comment by Samze** [comment]
In CF we treat the service instance name as a user chosen value. We support the `cf rename-service <old_name> <new_name>` command which currently only updates our internal representation and has no service broker interaction. For either solutions 1 or 2, brokers need to be made aware of renames. Update sounds like the place to do this. 

Note that CF also recently introduced optional named service bindings, as a way to more easily identify a binding in the app container's `VCAP_SERVICES` env, but there is no way today to rename them. 

@jakkahub do you have this requirement for service binding names too?

**Comment by jakkahub** [comment]
@Samze, we don't need this for service binding names.

**Comment by duglin** [comment]
from our perspective, we'd want it on bindings too

**Comment by zrob** [comment]
@jakkahub Could you help me understand what you're using the name for?

My first concern is that name is a mutable value, so it can change at any time after you have used it as a result of the provision.

**Comment by jakkahub** [comment]
@zrob OSB will create instances in our PaaS. It needs the user entered name because the created service instance is also exposed via our PaaS dashboards/CLI/REST API. (in addition to how user would access them via Ops Manager & CF CLI).  We want to create this using same user friendly name as was entered by the user in CF CLI (and not guid).

**Comment by mattmcneeney** [comment]
@jakkahub we spoke about this again on yesterday's call, and there were some concerns raised around passing the name of the service instance in the platform through to the broker.

The main concern was regarding the fact that platforms do not enforce service names to be unique, and so if a dashboard just showed the names (and not GUIDs too), then you could just see a number of service instances all with the name `my-instance`. Have you thought about how you would address that?

This flow would also require an additional update request being sent to the service broker when a developer renamed their service instance in the platform (i.e. through `cf rename-service`). Some brokers may reject a request when only metadata changes (the spec is [unclear](https://www.pivotaltracker.com/story/show/157186946) what a broker should respond in this scenario).

**Comment by mattmcneeney** [comment]
CF today only enforces uniqueness of service instance names in a specific space. Any aggregated view (as many dashboards provide) wouldn't be able to rely on uniqueness.

As you say, the dashboard _could_ restrict the view to a specific org/space, but not all dashboards use the platform's authorization models.

**Comment by duglin** [comment]
True but if the broker doesn't know about the platform's grouping (orgs, spaces) or who owns what, then it would be pretty odd for them to show more than just the one resource related to that dashboard URL - not to mention a huge security issue.

**Comment by duglin** [comment]
Rereading this issue it seems that most (if not all) of the usecases around this focus on giving the broker generated dashboard an opportunity to present the end user with the same user-defined name they specified when creating the instance (or binding) - mainly to provide a good UX.

Thinking about the Platform/app-specific things we send to the broker that are not of direct interest to the broker when creating instances and bindings: context, CF org, CF space, app-guid, route, k8s namespace, k8s clusterID.  Of those, it seems like route and k8s clusterID could change over time - even though we don't talk about a changing "route". Context could too, based on SAP's comments. While I might agree with an argument that says instance/binding "name" might change more often than these, "name" doesn't fundamentally feel like something that different to me.

As a brainstorming exercise... what if we defined a "parameter" on the Instance.Create() op called "instance_name" to carry this info? Since Instance.Update() already has the notion of updating parameters, it might be a natural way to carry/update this info.

**Comment by mattmcneeney** [comment]
I'll have a go at putting a PR together for this soon!

**Comment by mattmcneeney** [comment]
@jakkahub could you take a look at #544 and let us know if that will solve your use cases?

**Comment by jakkahub** [comment]
@mattmcneeney name field is part of the payload? As long as name field value is same as `SERVICE_INSTANCE` name in `cf create-service` command, it solves our use case. Any ETA for this ?

**Comment by mattmcneeney** [comment]
@jakkahub That is correct. Note that you will be relying on each platform to support this not only for provisioning, but also when updating a service instance. The name field won't be sent on the delete request.

**Comment by Samze** [comment]
A risk I see with this is if there are any brokers that exist today that reject requests from the platform when no `plan_id` or `parameters` field is specified. Broker behaviour for this has been undefined, see https://github.com/openservicebrokerapi/servicebroker/issues/538.

I see this slightly differently than when we add a new optional feature to the spec that a broker may not support, because platforms and users (at least CF) already support renaming service instances.

**Today** service instance rename will work in CF if my broker rejects update requests without a plan or parameters change.
**Tomorrow** service instance rename will fail in CF if my broker rejects update requests without a plan or parameters change.

I'm not sure this is a blocker to resolving this issue but I'd be curious to know what broker behaviour is.

Also if a broker rejects the request are we expecting platforms to fail the rename?

**Comment by mattmcneeney** [comment]
I would expect the platform to accept the name change, even if the broker rejected the update request. In my mind, we are giving the service broker information about what has been changed in the platform, not asking it to do some operation that we will await success/failure from.

**Comment by mattmcneeney** [comment]
The `instance_name` is now passed to service brokers via the [context object](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-context-object) so I believe this can be closed!
