### ISSUE TITLE
CloudFoundryContext

### ISSUE THREAD

**Issue by vivinjoseph9** [openservicebrokerapi/servicebroker#531]
Hi,
Previously the CloudFoundryContext had public constructors, but it has been changed to private.

	private CloudFoundryContext() {
		super(CLOUD_FOUNDRY_PLATFORM, null);
		this.organizationGuid = null;
		this.spaceGuid = null;
	}

	private CloudFoundryContext(String organizationGuid, String spaceGuid, Map<String, Object> properties) {
...

I use this class to create an CloudFoundryContext  object with organizationGuid and spaceGuid, however this is no longer possible.

Can you please let me know the intention behind the change and also the workaround for this? 

Thanks in advance.

Vivin.

**Comment by duglin** [comment]
Where is this code? It looks like it might be in some CF SDK/API thing. But its not from the OSBAPI spec (or WG) so I suspect you may want to open this issue in some CF github repo instead of this one.

**Comment by vivinjoseph9** [comment]
package org.springframework.cloud.servicebroker.model.CloudFoundryContext;

**Comment by duglin** [comment]
I don't know where that code lives, or who owns it but its not us so I'm going to close this issue since we can't fix it from here.  Perhaps you could open the issues in that repo. It might be over here: https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/model/Context.java
