### ISSUE TITLE
Add a unique-request-id header

### ISSUE THREAD

**Issue by jberkhahn** [openservicebrokerapi/servicebroker#584]
Would it be useful to have an optional header that is unique per-request, similar to Cloud Foundry's VCAP-request-ID? Basically an ID that is unique per request for logging and tracing purposes. In CF this is a unique ID used from the time the user submits a request to the front facing api server all the way through. It would be up to the platform to generate and track these IDs how they wanted.

Thoughts?

**Comment by duglin** [comment]
+1
There are other HTTP headers that we've talked about being useful ( like etag ), so it might nice to add a section to the spec to mention features (probably http features) that people may want to consider using. While we're not defining them as part of the spec, I think its useful to call them out (w/o duplicating their definition) so that people know that they're potentially good ideas to consider in their implementations.

**Comment by mattmcneeney** [comment]
This sounds sensible to me.

**Comment by duglin** [comment]
no concerns from people on the 8/21 call - so PR should come soon for further discussions

**Comment by mattmcneeney** [comment]
Great. Thanks @jberkhahn !
