### ISSUE TITLE
Broker sending 5xx on delete binding failure

### ISSUE THREAD

**Issue by amitmalav** [openservicebrokerapi/servicebroker#652]
Hello,
We have a stateful servicebroker which stores references to present instances and bindings.

On every unbind operation, broker first checks that the instance reference as well as binding reference exist in the state. Due to some inconsistencies (or manual intervention) sometimes it happens that binding reference exists but corresponding instance reference is deleted.
For this particular binding, when delete bind request comes, broker finds that instance reference is gone (Actual binding still exists). On this broker return 5xx because it is an internal server error for broker and binding is remembered by platform.
I don't see any other status codes mentioned in spec fitting in this scenario.

> Responses with any other status code MUST be interpreted as a failure and the Platform MUST continue to remember the Service Binding

I wanted to ask whether this behaviour of broker conforms with Osbapi spec.

**Comment by waterlink** [comment]
@amitmalav As a developer/admin working with a platform that integrates with this service broker, what do you expect to get in this scenario? _(for example, if you used a CLI tool to interact with a service binding)_

**Comment by georgi-lozev** [comment]
Hey @amitmalav 
As far as I understand your issue it looks like your broker is out of sync with the platform, because of some exceptional things with the broker persistency. This means that you have a reference to a service binding, but don't have a service instance that it is related to. So this makes it some kind of an orphaned binding.

Does it make sense for you as a broker author once you detect such kind of situation to clean up all resources associated with the orphaned binding and return `410 Gone` to the platform as per 
https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#response-8?
This should result in the binding being deleted from the platform.

You could also do some kind of similar logic for service instances, because I assume at some point in time you'll also receive a `DELETE` request for the missing one.

**Comment by amitmalav** [comment]
Thanks @waterlink @georgi-lozev 
Yes, it makes sense to do some kind of orphan mitigation in broker and when delete bind call comes, broker sends 410.
Currently broker returns 5xx on delete binding call as it is not able to delete the actual credentials because of missing references. Some mitigation logic in broker for detecting such scenarios will certainly help.
Thanks.
