### ISSUE TITLE
Named bindings support?

### ISSUE THREAD

**Issue by vaikas-google** [openservicebrokerapi/servicebroker#70]
Currently bindings don't have names, I think they should. That would make it easier to keep track of bindings, would allow multiple bindings between serviceA and serviceB, say a single database, but two connections to it? @bmelville you had another use case for it too, I don't recall...

**Comment by bmelville** [comment]
Without the ability to name a binding, the code that consumes the binding is bound to the name of the service you're binding to. If my service can bind to one of several different services that provide mysql 5.5, then ideally I shouldn't have to bind to "bobsmysql55", but can instead consume the "mysql55" binding, and just use that name when binding.

e.g.,

$ sc instances create bobsmysql55
# No name, requires that my consuming service pull binding information from the "bobsmysql55" binding.
$ sc bind myservice bobsmysql55
$ sc instances create myservice

vs.

$ sc instances create bobsmysql55
# Named, my service code always knows to pull the generic mysql 55 binding information from "mysql55".
$ sc bind myservice bobsmysql55 --name mysql55
$ sc instances create myservice

**Comment by duglin** [comment]
I think giving a binding a name is really only needed if you plan to bind the same app to the same service more than once. I'm not sure if CF purposely excluded this use case or not but I'd like to hear what @shalako's view is on this.

**Comment by duglin** [comment]
or in cases where you're dealing with a user-provided service.

**Comment by shalako** [comment]
The broker API intentionally leaves out display names for the instance and binding resources, as:
1.  the broker API was never intended to be user-facing, and
2. using display names as unique identifiers is a bad idea; namespacing requires tuples, names are mutable, etc.

In CF, we intentionally do not enable naming of bindings because: 
1. instance names are unique within a space so you would never have two service instances with the name `bobsmysql55`. Instead might have a db called `bobs-productdb` and another called `bobs-pricing-db`
2. a particular app can only be bound to a particular service instance once. why would you need more?

The broker API does support bindings without applications. The app_id field on the `PUT /v2/service_instances/:guid/service_bindings/:guid` endpoint is optional. CF supports what we call Service Keys, which enable users to create sets of credentials to be used by clients outside of CF. To think of it in reverse, the Bind operation in CF creates a service key and hands it to an app transparently. Hindsight being 20:20 I have, on occasion, thought the broker API resource should be `PUT /v2/service_instances/:guid/service_keys/:guid`as this is more generic. In most cases, the broker doesn't care who is consuming the response for the binding.

**Comment by bmelville** [comment]
To clarify, in my example bobsmysql55 is a service name, not an instance name. Currently in the CF model, bindings are keyed on the name of the service that has been instantiated and bound to, which requires the consuming app to bind to a particular service name in its consuming code to look up the binding. If bindings were nameable, a consuming service could always look for binding "foo", regardless of what type of service that binding is for, which allows it to bind to any service that meets its requirements (e.g., any mysql55 service, not just Bob's).

**Comment by shalako** [comment]
Thank you for the clarification. That is a reasonable and familiar use case. In CF this is addressed with tags provided by the user on creation of the service instance. So your app could always look for bound service instances with tags `foo`, `mysql55`, and/or `production`. User-provided tags are merged with a list provided by the service broker.

**Comment by angarg12** [comment]
@bmelville you mention the CF model, but speaking strictly about the SB API, do the same constraints apply?

The route for creating a binding is `PUT /v2/service_instances/:instance_id/service_bindings/:binding_id`. From our experience with the sample implementations and our PoC, :instance_id and :binding_id are unique, arbitrary strings. Isn't being able to assign arbitrary id's similar to naming? (with the caveat that they should be unique). Also, bindings are tied to instance_ids, not service names.

To clarify further, the docs say `Note: The :binding_id of a service binding is provided by the Cloud Controller`. But in our PoC there is no Cloud Controller, meaning that this value is assigned by users.

**Comment by bmelville** [comment]
Again, this issue is obsolete as it pertained to the open controller implementation that was at the time a part of this repo.
