### ISSUE TITLE
Why is bindingId globally unique and not unique per instance

### ISSUE THREAD

**Issue by harshalb007** [openservicebrokerapi/servicebroker#715]
**What is the problem?**
Trying to understand the purpose of bindingId

**Who does this affect?**
Affects the development of service broker we are developing

**Do you have any proposed solutions?**
Binding Id should be unique per instance

**Additional context**
We are developing Service broker as per OSBAPI standards.
While implementing create binding endpoint we found that as per OSBAPI specification, "binding_id MUST be a globally unique non-empty string. This ID will be used for future unbind requests, so the Service Broker will use it to correlate the resource it creates." 

According to our understanding, bindingId gives access to the instance for which the binding request is made. Then why is that OSBAPI suggests to have the bindingId **Globally Unique**.??

**Comment by harshalb007** [comment]
Hello,
Any update on this please?

**Comment by rsampaio** [comment]
@harshalb007 since version [2.15](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#changes-since-v215) we recommend never reusing any kind of ID either for service instances or bindings to avoid ID collision issues since UUID generation is usually trivial and for labels or categorization of bindings the recommendation is to use the `context` field. 

Please re-open this issue if you believe this is still an issue.
